version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: your_postgres_username
      POSTGRES_PASSWORD: your_postgres_password
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: aljodavis125@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    depends_on:
      - postgres
